 language: node_js
 node_js:
   - "0.10"

 before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install --quiet -g grunt-cli karma
  - npm install

 script: grunt
 
 addons:
  artifacts: true
  debug: true
  paths:
   - dist
   
deploy:
  provider: s3
  access_key_id: "AKIAJP647EKD6LJTOJIA"
  secret_access_key: "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"
  bucket: "travis-angular"
  skip_cleanup: true
  region: ireland